blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://imdhemy.com/laravel-iap-docs/
    about: Please read the documentation before asking questions.

  - name: 🙏 Q&A and Discussions
    url: https://github.com/imdhemy/appstore-iap/discussions
    about: Please ask and answer questions here.
